import unicodedata
# ============================================================
# CATÁLOGO OFICIAL DE CIUDADES Y DEPARTAMENTOS
# ============================================================

CIUDADES_ZOHO = [
    "Abejorral - Antioquia",
    "Abriaquí - Antioquia",
    "Alcalá - Valle Del Cauca",
    "Alejandría - Antioquia",
    "Algarrobo - Magdalena",
    "Almeida - Boyacá",
    "Amagá - Antioquia",
    "Amalfi - Antioquia",
    "Amazonas - Amazonas",
    "Anapoima - Cundinamarca",
    "Andalucía - Valle Del Cauca",
    "Andes - Antioquia",
    "Angelópolis - Antioquia",
    "Angostura - Antioquia",
    "Anorí - Antioquia",
    "Ansermanuevo - Valle Del Cauca",
    "Anzá - Antioquia",
    "Apartadó - Antioquia",
    "Apulo - Cundinamarca",
    "Apía - Risaralda",
    "Aracataca - Magdalena",
    "Aranzazu - Caldas",
    "Arauca - Arauca",
    "Arboletes - Antioquia",
    "Argelia - Antioquia",
    "Argelia - Valle Del Cauca",
    "Ariguaní - Magdalena",
    "Armenia - Antioquia",
    "Armenia - Quindío",
    "Ayapel - Córdoba",
    "Bahía Solano - Chocó",
    "Balboa - Risaralda",
    "Baranoa - Atlántico",
    "Barbosa - Antioquia",
    "Barichara - Santander",
    "Barrancabermeja - Santander",
    "Barranquilla - Atlántico",
    "Bello - Antioquia",
    "Belmira - Antioquia",
    "Belén De Umbría - Risaralda",
    "Betania - Antioquia",
    "Betulia - Antioquia",
    "Bogotá D.C. - Bogotá D.C.",
    "Bolívar - Bolívar",
    "Bolívar - Valle Del Cauca",
    "Boyacá - Boyacá",
    "Briceño - Antioquia",
    "Bucaramanga - Santander",
    "Buenaventura - Valle del Cauca",
    "Buenavista - Quindío",
    "Buenavista - Sucre",
    "Bugalagrande - Valle del Cauca",
    "Buriticá - Antioquia",
    "Caicedo - Antioquia",
    "Caicedonia - Valle Del Cauca",
    "Caimito - Sucre",
    "Cajicá - Cundinamarca",
    "Calarcá - Quindío",
    "Caldas - Antioquia",
    "Caldas - Caldas",
    "Cali - Valle del Cauca",
    "Calima - Valle Del Cauca",
    "Campamento - Antioquia",
    "Campo De La Cruz - Atlántico",
    "Cancún - Quintana Roo - México",
    "Candelaria - Atlántico",
    "Candelaria - Valle del Cauca",
    "Caquetá - Caquetá",
    "Caracolí - Antioquia",
    "Caramanta - Antioquia",
    "Carepa - Antioquia",
    "Carmen De Apicalá - Tolima",
    "Carolina - Antioquia",
    "Cartagena - Bolívar",
    "Cartago - Valle del Cauca",
    "Casanare - Casanare",
    "Cauca - Cauca",
    "Caucasia - Antioquia",
    "Cañasgordas - Antioquia",
    "Cerrito - Santander",
    "Cerro De San Antonio - Magdalena",
    "Cesar - Cesar",
    "Chalán - Sucre",
    "Chigorodó - Antioquia",
    "Chivolo - Magdalena",
    "Chocó - Chocó",
    "Chía - Cundinamarca",
    "Cimitarra - Santander",
    "Circasia - Quindío",
    "Cisneros - Antioquia",
    "Ciudad Bolívar - Antioquia",
    "Ciénaga - Magdalena",
    "Cocorná - Antioquia",
    "Colosó - Sucre",
    "Concepción - Antioquia",
    "Concordia - Antioquia",
    "Concordia - Magdalena",
    "Copacabana - Antioquia",
    "Corozal - Sucre",
    "Cota - Cundinamarca",
    "Coveñas - Sucre",
    "Cucuta - Norte de Santander",
    "Cáceres - Antioquia",
    "Córdoba - Córdoba",
    "Córdoba - Quindío",
    "Dabeiba - Antioquia",
    "Dagua - Valle Del Cauca",
    "Donmatías - Antioquia",
    "Dosquebradas - Risaralda",
    "Ebéjico - Antioquia",
    "El Bagre - Antioquia",
    "El Banco - Magdalena",
    "El Cairo - Valle Del Cauca",
    "El Carmen De Viboral - Antioquia",
    "El Cerrito - Valle del Cauca",
    "El Dovio - Valle del Cauca",
    "El Peñón - Santander",
    "El Piñón - Magdalena",
    "El Retén - Magdalena",
    "El Roble - Sucre",
    "El Santuario - Antioquia",
    "El Águila - Valle Del Cauca",
    "Entrerríos - Antioquia",
    "Envigado - Antioquia",
    "Espinal - Tolima",
    "Facatativá - Cundinamarca",
    "Filandia - Quindío",
    "Florencia - Caquetá",
    "Florida - Valle del Cauca",
    "Floridablanca - Santander",
    "Fredonia - Antioquia",
    "Fresno - Tolima",
    "Frontino - Antioquia",
    "Fundación - Magdalena",
    "Funza - Cundinamarca",
    "Fusagasugá - Cundinamarca",
    "Fómeque - Cundinamarca",
    "Fúquene - Cundinamarca",
    "Galapa - Atlántico",
    "Galeras - Sucre",
    "Ginebra - Valle Del Cauca",
    "Giraldo - Antioquia",
    "Girardot - Cundinamarca",
    "Girardota - Antioquia",
    "Girón - Santander",
    "Granada - Antioquia",
    "Guacarí - Valle Del Cauca",
    "Guadalajara De Buga - Valle Del Cauca",
    "Guadalupe - Antioquia",
    "Guainía - Guainía",
    "Guamal - Magdalena",
    "Guaranda - Sucre",
    "Guarne - Antioquia",
    "Guasca - Cundinamarca",
    "Guatapé - Antioquia",
    "Guataquí - Cundinamarca",
    "Guatavita - Cundinamarca",
    "Guaviare - Guaviare",
    "Guática - Risaralda",
    "Génova - Quindío",
    "Gómez Plata - Antioquia",
    "Heliconia - Antioquia",
    "Hispania - Antioquia",
    "Honda - Tolima",
    "Huila - Huila",
    "Ibagué - Tolima",
    "Inírida - Guainía",
    "Ipiales - Nariño",
    "Itagüí - Antioquia",
    "Ituango - Antioquia",
    "Jamundí - Valle del Cauca",
    "Jardín - Antioquia",
    "Jericó - Antioquia",
    "Juan De Acosta - Atlántico",
    "La Calera - Cundinamarca",
    "La Ceja - Antioquia",
    "La Celia - Risaralda",
    "La Cumbre - Valle Del Cauca",
    "La Estrella - Antioquia",
    "La Guajira - La Guajira",
    "La Mesa - Cundinamarca",
    "La Pintada - Antioquia",
    "La Tebaida - Quindío",
    "La Unión - Antioquia",
    "La Unión - Sucre",
    "La Unión - Valle Del Cauca",
    "La Victoria - Valle Del Cauca",
    "La Virginia - Risaralda",
    "Leticia - Amazonas",
    "Liborina - Antioquia",
    "Los Palmitos - Sucre",
    "Luruaco - Atlántico",
    "Maceo - Antioquia",
    "Magangué - Bolívar",
    "Majagual - Sucre",
    "Malambo - Atlántico",
    "Manatí - Atlántico",
    "Manizales - Caldas",
    "Marinilla - Antioquia",
    "Marsella - Risaralda",
    "Medellín - Antioquia",
    "Melgar - Tolima",
    "Meta - Meta",
    "Mistrató - Risaralda",
    "Mitú - Vaupés",
    "Mocoa - Putumayo",
    "Montebello - Antioquia",
    "Montenegro - Quindío",
    "Montería - Córdoba",
    "Morroa - Sucre",
    "Mosquera - Cundinamarca",
    "Murindó - Antioquia",
    "Mutatá - Antioquia",
    "Nariño - Antioquia",
    "Nariño - Nariño",
    "Nechí - Antioquia",
    "Necoclí - Antioquia",
    "Neira - Caldas",
    "Neiva - Huila",
    "Nemocón - Cundinamarca",
    "Nilo - Cundinamarca",
    "Norte De Santander - Norte de Santander",
    "Nueva Granada - Magdalena",
    "Nuquí - Chocó",
    "Obando - Valle Del Cauca",
    "Olaya - Antioquia",
    "Ovejas - Sucre",
    "Palmar De Varela - Atlántico",
    "Palmira - Valle del Cauca",
    "Palmito - Sucre",
    "Pasto - Nariño",
    "Pedraza - Magdalena",
    "Peque - Antioquia",
    "Pereira - Risaralda",
    "Peñol - Antioquia",
    "Piedecuesta - Santander",
    "Pijao - Quindío",
    "Pijiño Del Carmen - Magdalena",
    "Piojó - Atlántico",
    "Pivijay - Magdalena",
    "Plato - Magdalena",
    "Playa de Carmen - Quintana Roo - México",
    "Polonuevo - Atlántico",
    "Ponedera - Atlántico",
    "Popayán - Cauca",
    "Pradera - Valle Del Cauca",
    "Pueblo Rico - Risaralda",
    "Pueblorrico - Antioquia",
    "Puebloviejo - Magdalena",
    "Puerto Asís - Putumayo",
    "Puerto Berrío - Antioquia",
    "Puerto Carreño - Vichada",
    "Puerto Colombia - Atlántico",
    "Puerto Inírida - Guainía",
    "Puerto Nare - Antioquia",
    "Puerto Triunfo - Antioquia",
    "Putumayo - Putumayo",
    "Quibdó - Chocó",
    "Quimbaya - Quindío",
    "Quinchía - Risaralda",
    "Remedios - Antioquia",
    "Remolino - Magdalena",
    "Repelón - Atlántico",
    "Restrepo - Valle Del Cauca",
    "Retiro - Antioquia",
    "Ricaurte - Cundinamarca",
    "Riofrío - Valle Del Cauca",
    "Riohacha - La Guajira",
    "Rionegro - Antioquia",
    "Roldanillo - Valle Del Cauca",
    "Sabanagrande - Atlántico",
    "Sabanalarga - Antioquia",
    "Sabanalarga - Atlántico",
    "Sabanas De San Ángel - Magdalena",
    "Sabaneta - Antioquia",
    "Salamina - Magdalena",
    "Salento - Quindío",
    "Salgar - Antioquia",
    "Sampués - Sucre",
    "San Andrés - Archipiélago De San Andrés, Providencia y Santa Catalina",
    "San Andrés - San Andrés y Providencia",
    "San Andrés De Cuerquía - Antioquia",
    "San Benito Abad - Sucre",
    "San Carlos - Antioquia",
    "San Francisco - Antioquia",
    "San Gil - Santander",
    "San Jerónimo - Antioquia",
    "San Joaquín - Santander",
    "San José De Cúcuta - Norte de Santander",
    "San José De La Montaña - Antioquia",
    "San José De Miranda - Santander",
    "San José De Toluviejo - Sucre",
    "San José Del Guaviare - Guaviare",
    "San Juan De Betulia - Sucre",
    "San Juan De Urabá - Antioquia",
    "San Luis - Antioquia",
    "San Luis De Sincé - Sucre",
    "San Marcos - Sucre",
    "San Onofre - Sucre",
    "San Pedro - Sucre",
    "San Pedro - Valle Del Cauca",
    "San Pedro De Los Milagros - Antioquia",
    "San Pedro De Urabá - Antioquia",
    "San Rafael - Antioquia",
    "San Roque - Antioquia",
    "San Sebastián De Buenavista - Magdalena",
    "San Sebastián de Mariquita - Tolima",
    "San Vicente Ferrer - Antioquia",
    "San Zenón - Magdalena",
    "Santa Ana - Magdalena",
    "Santa Bárbara - Antioquia",
    "Santa Bárbara De Pinto - Magdalena",
    "Santa Cruz de Lorica - Córdoba",
    "Santa Fé De Antioquia - Antioquia",
    "Santa Lucía - Atlántico",
    "Santa Marta - Magdalena",
    "Santa Rosa De Cabal - Risaralda",
    "Santa Rosa De Osos - Antioquia",
    "Santander - Santander",
    "Santiago De Tolú - Sucre",
    "Santo Domingo - Antioquia",
    "Santo Tomás - Atlántico",
    "Santuario - Risaralda",
    "Sasaima - Cundinamarca",
    "Segovia - Antioquia",
    "Sesquilé - Cundinamarca",
    "Sevilla - Valle del Cauca",
    "Sibaté - Cundinamarca",
    "Silvania - Cundinamarca",
    "Simijaca - Cundinamarca",
    "Sincelejo - Sucre",
    "Sitionuevo - Magdalena",
    "Soacha - Cundinamarca",
    "Soledad - Atlántico",
    "Sonsón - Antioquia",
    "Sopetrán - Antioquia",
    "Sopó - Cundinamarca",
    "Suan - Atlántico",
    "Subachoque - Cundinamarca",
    "Sucre - Sucre",
    "Suesca - Cundinamarca",
    "Tabio - Cundinamarca",
    "Tarazá - Antioquia",
    "Tarso - Antioquia",
    "Tenerife - Magdalena",
    "Tenjo - Cundinamarca",
    "Titiribí - Antioquia",
    "Tocaima - Cundinamarca",
    "Tocancipá - Cundinamarca",
    "Toledo - Antioquia",
    "Tolima - Tolima",
    "Toro - Valle Del Cauca",
    "Trujillo - Valle Del Cauca",
    "Tubará - Atlántico",
    "Tulum - Quintana Roo - México",
    "Tuluá - Valle del Cauca",
    "Tunja - Boyacá",
    "Turbaco - Bolívar",
    "Turbará - Atlántico",
    "Turbo - Antioquia",
    "Támesis - Antioquia",
    "Ulloa - Valle Del Cauca",
    "Uramita - Antioquia",
    "Urrao - Antioquia",
    "Usiacurí - Atlántico",
    "Valdivia - Antioquia",
    "Valledupar - Cesar",
    "Valparaíso - Antioquia",
    "Vaupés - Vaupés",
    "Vegachí - Antioquia",
    "Venecia - Antioquia",
    "Versalles - Valle Del Cauca",
    "Vichada - Vichada",
    "Vigía Del Fuerte - Antioquia",
    "Vijes - Valle Del Cauca",
    "Villavicencio - Meta",
    "Villeta - Cundinamarca",
    "Yalí - Antioquia",
    "Yarumal - Antioquia",
    "Yolombó - Antioquia",
    "Yondó - Antioquia",
    "Yopal - Casanare",
    "Yotoco - Valle Del Cauca",
    "Yumbo - Valle del Cauca",
    "Zapayán - Magdalena",
    "Zaragoza - Antioquia",
    "Zarzal - Valle del Cauca",
    "Zipaquirá - Cundinamarca",
    "Zona Bananera - Magdalena",
]


# ============================================================
# DICCIONARIO DE NORMALIZACIÓN
# ============================================================
def normalizar_clave_ciudad(valor: str) -> str:
    valor = valor.strip().upper()

    return "".join(
        caracter
        for caracter in unicodedata.normalize("NFD", valor)
        if unicodedata.category(caracter) != "Mn"
    )


CITY_NORMALIZATION = {
    normalizar_clave_ciudad(ciudad): ciudad
    for ciudad in CIUDADES_ZOHO
}